repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    - id: black
      args: [-S]
-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    - id: flake8
      args: [--max-line-length=88]
-   repo: https://github.com/timothycrosley/isort
    rev: ''
    hooks:
    - id: isort
