version: "3"
services:
  web:
    image: ${DOCKER_REPO}/cobra:build
    ports:
      - "8765:8765"
    environment:
      - COBRA_REDIS_URLS=redis://redis1;redis://redis2;redis://redis3;redis://redis4;redis://redis5
      - COBRA_HOST=0.0.0.0
      - COBRA_PORT=8765
      - COBRA_APPS_CONFIG_CONTENT=${COBRA_APPS_CONFIG_CONTENT}
      - PYTHONUNBUFFERED=1
      - COBRA_PLUGINS=republish
      - PYTHONPATH=/etc/secret-volume
    volumes:
      #
      # To run in an environment similar to kubernete:
      # 1. mkdir /tmp/volume_cobra
      # 2. make sure /tmp is 'mountable' in Docker desktop
      # 3. run: cobra init
      # 4. cp $HOME/.cobra.yaml /tmp/volume_cobra/apps.yaml
      #    That file will be seen as /etc/secret-volume/apps.yaml in the container ran by docker-compose
      #
      - /tmp/volume_cobra:/etc/secret-volume
    networks:
      - cobra-net
    depends_on:
      - redis1
      - redis2

  redis1:
    image: redis:alpine
    networks:
      - cobra-net

  redis2:
    image: redis:alpine
    networks:
      - cobra-net
        
networks:
  cobra-net:
